-- v3 schema: new database only. Existing v2 databases use scripts.migrate.
BEGIN;
CREATE TABLE schema_version (version integer PRIMARY KEY CHECK (version = 2));
INSERT INTO schema_version VALUES (2);
CREATE TABLE students (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id varchar(50) UNIQUE NOT NULL CHECK (length(trim(student_id)) > 0),
    full_name varchar(100) NOT NULL CHECK (length(trim(full_name)) > 0),
    phone_encrypted text NOT NULL,
    consent_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE student_faces (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    embedding_encrypted text NOT NULL
);
CREATE INDEX student_faces_student_idx ON student_faces(student_id);
CREATE TABLE authorized_terminals (
    terminal_uuid varchar(100) PRIMARY KEY,
    token_hash char(64) NOT NULL,
    location_name varchar(100) NOT NULL,
    direction varchar(3) NOT NULL CHECK (direction IN ('IN','OUT')),
    active boolean NOT NULL DEFAULT true
);
CREATE TABLE attendance_logs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    terminal_uuid varchar(100) NOT NULL REFERENCES authorized_terminals(terminal_uuid),
    event_id uuid NOT NULL,
    check_in_time timestamptz NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    status varchar(50) NOT NULL,
    event_type varchar(3) NOT NULL CHECK (event_type IN ('IN','OUT')),
    review_required boolean NOT NULL DEFAULT false,
    UNIQUE (terminal_uuid, event_id)
);
CREATE INDEX attendance_student_time_idx ON attendance_logs(student_id, check_in_time DESC);
CREATE INDEX attendance_time_idx ON attendance_logs(check_in_time DESC, id DESC);
CREATE TABLE scan_receipts (
    terminal_uuid varchar(100) NOT NULL REFERENCES authorized_terminals(terminal_uuid),
    event_id uuid NOT NULL,
    payload_hash char(64) NOT NULL,
    response jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (terminal_uuid, event_id)
);
CREATE INDEX scan_receipts_created_idx ON scan_receipts(created_at);
CREATE TABLE audit_events (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action varchar(50) NOT NULL,
    subject varchar(100) NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now()
);
-- Additive upgrade from schema v2; run with scripts.migrate, inside its transaction.
ALTER TABLE schema_version DROP CONSTRAINT schema_version_version_check;
UPDATE schema_version SET version = 3;
ALTER TABLE schema_version ADD CHECK (version = 3);
CREATE TABLE admin_users (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username varchar(100) UNIQUE NOT NULL CHECK (username = lower(username)),
    password_hash text NOT NULL,
    role varchar(10) NOT NULL CHECK (role IN ('owner', 'operator', 'viewer')),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE admin_sessions (
    token_hash char(64) PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    csrf_hash char(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX admin_sessions_user_idx ON admin_sessions(user_id);
CREATE INDEX admin_sessions_expiry_idx ON admin_sessions(expires_at);
CREATE TABLE auth_rate_limits (
    bucket_key char(64) PRIMARY KEY,
    attempts integer NOT NULL DEFAULT 1,
    expires_at timestamptz NOT NULL
);
CREATE INDEX auth_rate_expiry_idx ON auth_rate_limits(expires_at);
ALTER TABLE audit_events ADD COLUMN actor_id bigint;
ALTER TABLE audit_events ADD COLUMN actor_username varchar(100);
CREATE INDEX audit_events_time_idx ON audit_events(occurred_at DESC, id DESC);

COMMIT;
