import {PGlite} from '@electric-sql/pglite';
import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(fs.readFileSync(new URL('../campus_attendance.sql',import.meta.url),'utf8'));
await db.query("INSERT INTO students(student_id,full_name,phone_encrypted) VALUES ('S001','Synthetic Student','encrypted')");
await db.query("INSERT INTO student_faces(student_id,embedding_encrypted) VALUES (1,'encrypted')");
await db.query("INSERT INTO authorized_terminals(terminal_uuid,token_hash,location_name,direction) VALUES ('gate',$1,'Test','IN')",['a'.repeat(64)]);
await db.exec('BEGIN');
await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['gate:request']);
await db.query("SELECT * FROM authorized_terminals WHERE terminal_uuid='gate' FOR SHARE");
await db.query('SELECT id FROM students WHERE id=1 FOR UPDATE');
await db.query("INSERT INTO attendance_logs(student_id,terminal_uuid,event_id,check_in_time,status,event_type,review_required) VALUES (1,'gate','00000000-0000-0000-0000-000000000001',now(),'Late Entry','IN',false)");
await db.query("INSERT INTO scan_receipts(terminal_uuid,event_id,payload_hash,response) VALUES ('gate','00000000-0000-0000-0000-000000000001',$1,$2)",['b'.repeat(64),JSON.stringify({success:true})]);
await db.exec('COMMIT');
const log=await db.query('SELECT s.student_id AS roll_number,s.full_name AS name,a.* FROM attendance_logs a JOIN students s ON s.id=a.student_id ORDER BY a.check_in_time DESC,a.id DESC LIMIT $1 OFFSET $2',[50,0]);
assert.equal(log.rows[0].roll_number,'S001');
const stats=await db.query("SELECT (SELECT count(*) FROM students) AS total_students,count(DISTINCT student_id) FILTER (WHERE event_type='IN') AS today_present,count(DISTINCT student_id) FILTER (WHERE event_type='IN' AND status='Late Entry') AS late_entries FROM attendance_logs WHERE check_in_time >= $1 AND check_in_time < $2",['2020-01-01','2030-01-01']);
assert.equal(Number(stats.rows[0].today_present),1);
await db.exec('BEGIN');await db.query("INSERT INTO students(student_id,full_name,phone_encrypted) VALUES ('S002','Rollback','encrypted')");await db.exec('ROLLBACK');
assert.equal(Number((await db.query('SELECT count(*) AS n FROM students')).rows[0].n),1);
await db.query('DELETE FROM students WHERE id=1');
for(const table of ['attendance_logs','student_faces'])assert.equal(Number((await db.query('SELECT count(*) AS n FROM '+table)).rows[0].n),0);
assert.equal(Number((await db.query('SELECT count(*) AS n FROM scan_receipts')).rows[0].n),1);
await db.close();console.log('SQL smoke passed: schema, transactions, lock syntax, joins, stats, rollback, cascades, retained receipts. NOT a native concurrency test.');
const dom=new JSDOM(fs.readFileSync(new URL('../static/index.html',import.meta.url),'utf8'),{url:'http://127.0.0.1:8000',runScripts:'outside-only'});
const w=dom.window;w.setInterval=()=>0;w.AbortSignal=AbortSignal;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
let fail=false;let role='owner';let requests=[];
w.fetch=async (url,options)=>{requests.push({url,options});if(fail)return{ok:false,status:503,json:async()=>({detail:'Database temporarily unavailable'})};const data=url.endsWith('login')?{user:{id:1,username:'synthetic',role},csrf_token:'synthetic-csrf'}:url.endsWith('config')?{class_start:'09:00',class_end:'16:00',timezone:'Asia/Kolkata'}:url.endsWith('dashboard-stats')?{total_students:0,today_present:0,today_absent:0,late_entries:0}:[];return {ok:true,status:200,json:async()=>data};};
w.eval(fs.readFileSync(new URL('../static/app.js',import.meta.url),'utf8'));
assert.match(w.document.getElementById('table-body').textContent,/Connect to view/);
w.document.getElementById('username').value='synthetic';w.document.getElementById('password').value='synthetic-password';
await w.document.getElementById('auth').onsubmit({preventDefault(){}});
assert.equal(w.document.getElementById('total').textContent,'0');assert.equal(w.document.getElementById('present').textContent,'0');assert.equal(w.document.getElementById('password').value,'');
assert.equal(w.document.getElementById('users-panel').hidden,false);
assert.equal(requests.at(-1).options.headers['X-CSRF-Token'],'synthetic-csrf');
assert.equal(requests.at(-1).options.credentials,'same-origin');
fail=true;await w.document.getElementById('refresh').onclick();assert.equal(w.document.getElementById('total').textContent,'—');assert.match(w.document.getElementById('notice').textContent,/unavailable/);
fail=false;await w.document.getElementById('logout').onclick();assert.match(w.document.getElementById('notice').textContent,/Locked/);assert.equal(w.localStorage.length,0);
role='viewer';w.document.getElementById('password').value='synthetic-password';await w.document.getElementById('auth').onsubmit({preventDefault(){}});
assert.equal(w.document.getElementById('enrollment-panel').hidden,true);assert.equal(w.document.querySelector('[data-tab="users"]').hidden,true);
role='operator';w.document.getElementById('password').value='synthetic-password';await w.document.getElementById('auth').onsubmit({preventDefault(){}});
assert.equal(w.document.getElementById('enrollment-panel').hidden,false);assert.equal(w.document.getElementById('terminal-panel').hidden,true);
w.close();console.log('DOM smoke passed: staff login, role controls, CSRF, zero counters, failed refresh, logout and no localStorage credentials. NOT a visual or camera test.');
